chore(order): clean up workflow files

diff --git a/.github/workflows/pr-order-service.yml b/.github/workflows/pr-order-service.yml
--- a/.github/workflows/pr-order-service.yml
+++ b/.github/workflows/pr-order-service.yml
@@ -1,56 +1,56 @@
-# name: Order Service CI
-# on:
-#   push:
-#     branches:
-#       - main
-#     paths:
-#       - services/order/**
-#   pull_request:
-#     branches:
-#       - "*"
-#     paths:
-#       - services/order/**
+name: Order Service CI
+on:
+  push:
+    branches:
+      - main
+    paths:
+      - services/order/**
+  pull_request:
+    branches:
+      - "*"
+    paths:
+      - services/order/**
 
-# permissions:
-#   pull-requests: write
-#   id-token: write
-#   contents: write
+permissions:
+  pull-requests: write
+  id-token: write
+  contents: write
 
-# jobs:
-#   build:
-#     name: Testing
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout
-#         id: checkout-code
-#         uses: actions/checkout@v4
-#         with:
-#           fetch-depth: 0
+jobs:
+  build:
+    name: Testing
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        id: checkout-code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-#       - name: Run Coverage
-#         working-directory: services/order
-#         run: |
-#           go test ./... -coverprofile=order-coverage.out -covermode=atomic -cover -short ./...
-#           cp order-coverage.out ../../order-coverage.out
+      - name: Run Coverage
+        working-directory: services/order
+        run: |
+          go test ./... -coverprofile=order-coverage.out -covermode=atomic -cover -short ./...
+          cp order-coverage.out ../../order-coverage.out
 
-#       - name: Validate coverage
-#         id: coverage
-#         uses: vladopajic/go-test-coverage@v2
-#         with:
-#           config: ./services/order/.coverageconfig.yml
+      - name: Validate coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2
+        with:
+          config: ./services/order/.coverageconfig.yml
 
-#       - name: Post coverage report
-#         if: github.ref_name != 'main'
-#         uses: thollander/actions-comment-pull-request@v3
-#         with:
-#           github-token: ${{ secrets.GITHUB_TOKEN }}
-#           comment-tag: coverage-report
-#           message: |
-#             go-test-coverage report:
-#             ```
-#             ${{ fromJSON(steps.coverage.outputs.report) }}```
+      - name: Post coverage report
+        if: github.ref_name != 'main'
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          message: |
+            go-test-coverage report:
+            ```
+            ${{ fromJSON(steps.coverage.outputs.report) }}```
 
-#       - name: Finally check coverage
-#         if: steps.coverage.outcome == 'failure'
-#         shell: bash
-#         run: echo "coverage check failed" && exit 1
+      - name: Finally check coverage
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
